spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    kubernetes:
      enabled: true
      discovery:
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
        all-namespaces: true
        enabled: true

server:
  port: 9762